name: Refactor release

on:
  push:
    branches:
      - 'refactor'

jobs:

  refactor_release:
    runs-on: ubuntu-latest
    container: golang:1.20
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Vet
        run: |
          go vet ./...

      - name: Compile all
        run: |
          make all

      - name: Release artifacts
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          makeLatest: false
          prerelease: true
          tag: refactor
          updateOnlyUnreleased: true
          artifacts: "bin/*"
