name: Go

on:
  pull_request:
    branches: 
      - main

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.16.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Cache deps
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Vet
      run: |
        go vet ./...

    - name: Compile statictest
      run: |
        go build -o=cmd/statictest/statictest cmd/statictest/main.go

    - name: Compile shortenertest
      run: |
        go test -c -o=cmd/shortenertest/shortenertest ./cmd/shortenertest/...
